### PR TITLE
Error code for not implemented has been included in the specification 

### PR DESCRIPTION
**Pull request by ypriverol**
@edeutsch I have added the Error code.

### CODE REVIEW

**Comment by ypriverol** [comment]
> Seems good, thanks. Except why "The following end point"? There is no "following" is there? How about just "This end point" (the one generating the 501)

Done.

**Comment by edeutsch** [comment]
What does it mean "All checks have failed"? (beyond the obvious)

**Comment by edeutsch** [comment]
Are we good to merge this? Still waiting on me for something? I'm expecting @ypriverol to merge?

**Comment by ypriverol** [comment]
Here new change related to the fileName in `spectra` and `psm` end points.

**Pull request merged**
